### ISSUE TITLE
Fail gracefully if item does not exist

### ISSUE THREAD

**Issue by deed02392** [onyxraven/zsh-osx-keychain#1]
Currently there's no way to gracefully handle if the keychain item doesn't already exist, which makes self setup (if key, use, else, prompt user to set) require forking this code.

**Comment by onyxraven** [comment]
If you have a PR for the prompt case, I'd welcome it. But be aware, it should also be friendly to non-interactive terminals, and do something (like return and error code) when you can't prompt.

**Comment by deed02392** [comment]
Maybe my output can be an update to the readme doc. I am trying to figure out a graceful way to handle failure to read. Your function returns 1 if the item doesn't exist, but how do I access that when I am trying:

```bash
 $ local apikey=$(keychain-environment-variable foo-api-key)
 echo $? # outputs 0 even though foo-api-key is not set
```

**Comment by deed02392** [comment]
I tried this:

```zsh
  apikey=$(keychain-environment-variable api-key)
  if [ $? -ne 0 ]; then
    echo "Enter your api-key - will be stored on default keychain for future use"
    set-keychain-environment-variable api-key
  fi
```
but the resulting password stored had garbage either side of it, I assume from pasting it?

```[200~pastedvalue[201~```

**Comment by deed02392** [comment]
Since I wanted to implement this in a Zle function I could not use `read` or even `zle` again since recursive `zle` is not supported (yet).

Instead I rewrote the users command buffer to call `security` directly to set a secret.

On subsequent calls the read succeeds.
